### PR TITLE
ci: Drop support for Python `3.8`

### LINKED ISSUE #3497: Preparing for Python 3.8 EOL
### What is your suggestion?

Based on [PEP 569](https://peps.python.org/pep-0569/#lifespan) and [devguide](https://devguide.python.org/versions/) official support for Python 3.8 will be ending in **October 2024**. At the time of writing this is 2-3 months away.

The last bump `altair` had was https://github.com/vega/altair/pull/3100 which was a few weeks after 3.7 EOL.

I see one small, and another larger PR to come from this.

# Testing

Currently Python 3.9 is not part of the github test matrix:
https://github.com/vega/altair/blob/f2ac0a14294da11cd29cf57753d774f9a71ff173/.github/workflows/build.yml#L10

However I had previously added to the hatch test matrix, providing coverage [locally](https://github.com/vega/altair/blob/main/CONTRIBUTING.md#failures-on-specific-python-versions) with `hatch test --all`:
https://github.com/vega/altair/blob/f2ac0a14294da11cd29cf57753d774f9a71ff173/pyproject.toml#L139-L140

This one is a pretty minor fix, and could be added now - since eventually it will be the lower bound.

# Bumping `build.requires-python`
I'm not proposing doing this *immediately*, just to keep on the radar and present some findings.

https://github.com/vega/altair/blob/f2ac0a14294da11cd29cf57753d774f9a71ff173/pyproject.toml#L35

## Related Projects
Descending order by `requires-python`:

| requires-python | project | source |
|--------|--------|--------|
| 3.10 | `pandas` | https://github.com/pandas-dev/pandas/blob/67a58cddc2f8c0e30cb0123589947d9b3f073720/pyproject.toml#L28 |
| 3.10 | `numpy` | https://github.com/numpy/numpy/blob/d3d7b55616a062d91af8e20d2a4eb817a41cea56/pyproject.toml#L19 |
| 3.10 | `ibis` | https://github.com/ibis-project/ibis/blob/aa1eff703a0b53899b5e70e1a08ac23ee23e2a2c/pyproject.toml#L39 | 
| 3.10 | `scipy` | https://github.com/scipy/scipy/blob/a1ea3b4a5af724b47cc22160b379db563fbf83ed/pyproject.toml#L47 |
| 3.10 | `ipython` | https://github.com/ipython/ipython/blob/ad07901d8cf6fb874262c6387bd24d9e5a284144/pyproject.toml#L23 |
| 3.9 | `geopandas` | https://github.com/geopandas/geopandas/blob/2d2d94b1a67e0f1cff7bcd9d2bf4f603c936d027/pyproject.toml#L22 |
| 3.8 | `pyarrow` | https://github.com/apache/arrow/blob/a88f0cd0368f81f1b9243d443cd571d09242c5b1/python/pyproject.toml#L37 |
| 3.8 | `polars` | https://github.com/pola-rs/polars/blob/69b20646fa8090d76241522f0f8b8b24edcb4ae0/py-polars/pyproject.toml#L13 |
| 3.8 | `jsonschema` | https://github.com/python-jsonschema/jsonschema/blob/d2aa2ba124417484eb8ed0950d48527a50b0f773/pyproject.toml#L11 | 3.8 | `jinja2` | https://github.com/pallets/jinja/blob/f8323cf4042ab058ac5b11743614c63308798541/pyproject.toml#L18 | 

### Have you considered any alternative solutions?

_No response_

### PR DESCRIPTION
**Pull request by dangotbanned**
Closes #3497

# Note for reviewers
Most of the changes in this PR were handled by `ruff`, and relate to these `3.9` changes:
- https://docs.python.org/3.9/whatsnew/3.9.html#type-hinting-generics-in-standard-collections
- https://docs.python.org/3/library/typing.html#deprecated-aliases

Essentially, this looks like a big job but excluding (https://github.com/vega/altair/pull/3647/commits/c7658977e44a26972809961b0f9360064013391b) this is actually quite a minor PR

# Tasks
- [x] Update `build.yml`, minimum `pandas`, `numpy` (https://github.com/vega/altair/pull/3647/commits/da300c381d977c2aa8f63aaf0d580b6ae35b41b8)
- [x] Update `pyproject.toml` (https://github.com/vega/altair/pull/3647/commits/c694f6595f0597d101fbe4976aafc825f53b5764)
- [x] Rerun `ruff` and fix errors (https://github.com/vega/altair/pull/3647/commits/c7658977e44a26972809961b0f9360064013391b)
    - See (https://github.com/vega/altair/pull/3618#issuecomment-2422278277)
- [x] Fix ci `3.9` error for `ibis` (https://github.com/vega/altair/pull/3647/commits/59952020ed025cae752c91db1fa4839986b17a33)
	- (https://github.com/vega/altair/actions/runs/11438192554/job/31819283249?pr=3647)
	- Not seeing this locally with `hatch test --python 3.9`

### CODE REVIEW

**Comment by dangotbanned** [comment]
The CI error is a bit cryptic, but I think #3494 was due to similar error

@MarcoGorelli if you're available, I just wanted to run this by you in case you can spot the issue in 

https://github.com/vega/altair/actions/runs/11438192791/job/31819284620?pr=3647

I think it is this line, but quite unsure why this has become an issue here

https://github.com/vega/altair/blob/61f1db7b7a9c06596823b2da66ad189db0804269/tests/vegalite/v5/test_api.py#L34

**Comment by dangotbanned** [comment]
Not sure how to unblock the expected checks for:
- `py 3.8 js 3.0`
- `py 3.8 js latest`

They were removed in [`da300c3` (#3647)](https://github.com/vega/altair/pull/3647/commits/da300c381d977c2aa8f63aaf0d580b6ae35b41b8)

**Comment by mattijn** [comment]
I've removed the rules in the rule set for Python version 3.8. All checks are now green, is that in line what is expected? I did not look careful in CI was still red before I made the change to the ruleset.

**Comment by dangotbanned** [comment]
> I've removed the rules in the rule set for Python version 3.8. All checks are now green, is that in line what is expected? I did not look careful if the CI in this PR was still red before I made the change to the ruleset.

Thanks @mattijn 

It was all green except, with the two `3.8` jobs mentioned in https://github.com/vega/altair/pull/3647#issuecomment-2426481888 marked as expected. 
No reds since [`5995202` (#3647)](https://github.com/vega/altair/pull/3647/commits/59952020ed025cae752c91db1fa4839986b17a33)

**Comment by mattijn** [comment]
Is pandas version 1.1.3 the minimum supported version for Python 3.9?

**Comment by dangotbanned** [comment]
> Is pandas version 1.1.3 the minimum supported version for Python 3.9?

That was the earliest I found going through the release notes @mattijn 

- https://pandas.pydata.org/docs/whatsnew/v1.1.3.html
- https://numpy.org/devdocs/release/1.19.3-notes.html

I think `numpy` had some level of support before `1.19.3`, but it looked like more of an announcement in that version

**Comment by mattijn** [comment]
Thanks! Moving forward🥳

**Pull request merged**
