### PR TITLE
Adding extra configure_* methods.

### PR DESCRIPTION
**Pull request by ellisonbg**

### CODE REVIEW

**Comment by ellisonbg** [comment]
I should probably add some tests for these before we merge.

**Comment by jakevdp** [comment]
Very nice! This will be a nice enhancement. I think tests should be straightforward: the three ways of configuring (via a ``Layer`` initialization argument, via ``config()``, and via ``config_*()``) should all result in the same output code.

The last piece of this is to make the code generation use this approach when possible. That also shouldn't be too difficult: it should be very similar to the way we enable keywords in the ``mark_*()`` methods currently.

**Comment by ellisonbg** [comment]
OK I have added tests for everything and simplified the implementation. Waiting for travis now...

**Comment by ellisonbg** [comment]
@jakevdp can you update the code generation to use the `configure_*` methods - no hurry.

**Comment by jakevdp** [comment]
Code generation update in #127

**Pull request merged**
