### PR TITLE
doc: add example, interval selection on a map

### PR DESCRIPTION
**Pull request by mattijn**
This PR adds a new example showing how one can use the selection interval on a map:

image

ref: #1232

### CODE REVIEW

**Comment by mattijn** [comment]
@binste, do you know how I can avoid this mypy error?
```
error: Cannot find implementation or library stub 
for module named "geopandas"  [import-not-found]
```

**Comment by binste** [comment]
In the `lint` workflow, only normal and `dev` dependencies are being installed. `geopandas` is a doc dependency so far and hence, mypy can't find it. As we now use it in this example which is also a test, geopandas should be moved from `doc` dependencies to `dev` in pyproject.toml. As geopandas is not a typed package as far as I know, you'll first get another error:
```
tests/examples_methods_syntax/interval_selection_map_quakes.py:11: error: Skipping analyzing "geopandas": module is installed, but missing library stubs or py.typed marker  [import-untyped]
```
which you can solve by adding `geopandas.*` to the modules under `[[tool.mypy.overrides]]` in `pyproject.toml`.

These two steps should make mypy happy :)

**Review by binste — APPROVED** [review]
Great example! Could you harmonize the usage of single and double quotes to one of them (my preference is double quotes). Apart from that, looks good to me.

**Comment by mattijn** [comment]
Thanks for the review @binste. Applied your suggestions. Tests are happy, so merging.

**Comment by binste** [comment]
I like the idea of "happy" tests. Petition for GitHub to replace the red X and green check mark with grumpy and happy smilies ;)

**Pull request merged**
