### PR TITLE
refactor(docs, ruff): Add `pydocstyle` rules

### PR DESCRIPTION
**Pull request by dangotbanned**
Follow-up discussed in: https://github.com/vega/altair/issues/3430#issuecomment-2148981414

This PR defines and applies a docstring style, for consistent and readable docs.

The style is based on [numpydoc](https://numpydoc.readthedocs.io/en/latest/format.html) with some tweaks that have already been introduced to `expr` in https://github.com/vega/altair/pull/3466#discussion_r1671952334

I have not added any new rules to *that* config.
However, testing on the generated code identified some rules that needed to be ignored.

---

This style is strictly applied to **generated code only**, until the final style has been approved.

One caveat is that docstring **code** formatting [rules](https://docs.astral.sh/ruff/formatter/#docstring-formatting) are not enabled yet - as they only affect non-generated code.

### CODE REVIEW

**Comment by dangotbanned** [comment]
@binste @mattijn @joelostblom @jonmmease 

I've left this on draft for discussion, with the hope to apply whatever style is agreed upon to the rest of the codebase. 
I wasn't planning on opening another PR before `v5.4.0`, but I've been writing more docs lately and have been missing the autofixes.

Just wanted to be clear that this is ready for "review", but I'm not looking to merge only the changes to generated code, if that makes sense?

**Comment by mattijn** [comment]
All good from my side. Just one note, that you are surely already aware of, many code including docstrings is auto generated. Thus if you want to apply numpydoc formatting style to them it should be within the code that generate this.

**Comment by mattijn** [comment]
I know see your line stating:

> This style is strictly applied to generated code only

👍

**Review by mattijn — APPROVED** [review]

**Comment by dangotbanned** [comment]
> All good from my side. Just one note, that you are surely already aware of, many code including docstrings is auto generated. Thus if you want to apply numpydoc formatting style to them it should be within the code that generate this.

> I now see your line stating:
> 
> > This style is strictly applied to generated code only
> 
> 👍

Thanks @mattijn 

For reference, running on the rest of the codebase:


```cmd
>>> ruff check --statistics
Found 472 errors.
[*] 410 fixable with the `--fix` option.
195     D400    [*] ends-in-period
174     D213    [*] multi-line-summary-second-line
 59     D205    [ ] blank-line-after-summary      
 13     D200    [*] fits-on-one-line
 11     D202    [*] no-blank-line-after-function  
  6     D407    [*] dashed-underline-after-section
  4     D403    [*] first-line-capitalized        
  3     D209    [*] new-line-after-last-paragraph 
  3     D404    [ ] docstring-starts-with-this    
  1     D300    [*] triple-single-quotes
  1     D406    [*] new-line-after-section-name   
  1     D410    [*] no-blank-line-after-section   
  1     D411    [*] no-blank-line-before-section 
```

Showing the diff wouldn't be very helpful, but if you're interested in seeing examples for each code at [pydocstyle-d](https://docs.astral.sh/ruff/rules/#pydocstyle-d)

**Comment by dangotbanned** [comment]
After further thought, the non-generated code provides a greater range of examples.

See https://github.com/vega/altair/pull/3493#commits-pushed-93df21a for more variety.

---

> One caveat is that docstring **code** formatting [rules](https://docs.astral.sh/ruff/formatter/#docstring-formatting) are not enabled yet - as they only affect non-generated code.

This part still applies, I'll leave that until there's another approval

**Review by binste — APPROVED** [review]
Configuration works for me as well. Thanks for setting it up and implementing the manual fixes! Adding my approval as well as a confirmation :)

**Comment by dangotbanned** [comment]
Thanks @binste @mattijn for the approvals, apologies that I'm asking for another 


If anyone has any strong opinions on the change in [`4ccad22` (#3493)](https://github.com/vega/altair/pull/3493/commits/4ccad22c7f54dc9ed54532a211526225aa19c662)

My suggestion would be to revisit during the review of 
- https://github.com/vega/altair/pull/3492

That will end up with more docstring code block examples once finished. 
I personally don't mind either style. Maybe leaning towards the `88` one to account for long class names?

**Review by mattijn — APPROVED** [review]

**Pull request merged**
