### PR TITLE
chore: fixup ruff-mypy CI job due to Ruff change

### PR DESCRIPTION
**Pull request by MarcoGorelli**
Due to https://github.com/astral-sh/ruff/pull/12106/files, this is currently failing some CI runs

### CODE REVIEW

**Comment by dangotbanned** [comment]
@MarcoGorelli 

I found I needed to bump `pyproject.toml` to get `hatch` to rebuild the env locally, to not reintroduce the old fix https://github.com/vega/altair/commit/f95be1ae3a7acd12e014f43cfabde47114e0156c

Not sure if that's been an issue for you as well

**Comment by MarcoGorelli** [comment]
thanks @dangotbanned - is that commit part of a PR? should I close in favour of that, or just bump ruff here?

**Comment by dangotbanned** [comment]
> thanks @dangotbanned - is that commit part of a PR? should I close in favour of that, or just bump ruff here?

It is part of https://github.com/vega/altair/pull/3427 but I only added to get CI passing there

Probably best to fix it here, since there's another PR active that with the same issue https://github.com/vega/altair/actions/runs/9827488485/job/27130222466?pr=3459

**Comment by mattijn** [comment]
Thanks for the PR @MarcoGorelli and review @dangotbanned! Tests are happy, merging!

**Pull request merged**
