### PR TITLE
maint: GitHub action include `python-version` 3.12

### PR DESCRIPTION
**Pull request by mattijn**
Python 3.12 was released recently, this PR updates our GitHub action to also test against python 3.12. This PR is currently failing because pyarrow does not yet publish builds for python 3.12, see https://github.com/apache/arrow/issues/37880. 

By including `python-version` 3.12 I dropped 3.9 to avoid the number of tests that are run in parallel. So it becomes `python-version: ["3.8", "3.10", "3.11", "3.12"]`, not sure if that is a good idea.

### CODE REVIEW

**Comment by jonmmease** [comment]
> By including python-version 3.12 I dropped 3.9 to avoid the number of tests that are run in parallel. So it becomes python-version: ["3.8", "3.10", "3.11", "3.12"], not sure if that is a good idea.

👍  Yeah, I think that's reasonable

**Comment by binste** [comment]
Thanks! Sounds good to me too.

**Comment by binste** [comment]
Could you add 3.12 also under `classifiers` in `pyproject.toml`?

**Comment by mattijn** [comment]
Tests passing, merging

**Pull request merged**
