### PR TITLE
ci: include optional dependencies for Polars backend in ibis-framework install

### PR DESCRIPTION
**Pull request by MarcoGorelli**
I'm seeing a CI failure in the downstream tests: https://github.com/narwhals-dev/narwhals/actions/runs/10055785067/job/27793203912?pr=587

Thanks for contributing to Altair!

Please follow these guidelines when submitting your PR:

- Describe the purpose of the changes in PR, so that it is easy to understand the implication of the suggested changes.
    - Here is a [helpful article about writing effective PR descriptions](https://medium.com/@greenberg/writing-pull-requests-your-coworkers-might-enjoy-reading-9d0307e93da3).
- Include unit tests and documentation for new features
- Ensure that the title is a concise [semantic commit message](https://www.conventionalcommits.org/) (e.g. "feat: Add `embed_options` to charts").
    - Append `!` if the change is breaking (e.g. "fix!: Raise error when `embed_options` is `None`")

### CODE REVIEW

**Comment by mattijn** [comment]
Seems Altair is not including the `pyarrow-hotfix` package, from what I see what is included within `ibis-framework[polars]`:

https://github.com/ibis-project/ibis/blob/aa1eff703a0b53899b5e70e1a08ac23ee23e2a2c/pyproject.toml#L165C46-L165C60
```python
polars = ["polars", "packaging", "pyarrow", "pyarrow-hotfix"]
```

And what is not included within Altair pyproject.toml:
https://github.com/vega/altair/blob/f2ac0a14294da11cd29cf57753d774f9a71ff173/pyproject.toml#L67-L83

**Comment by mattijn** [comment]
This hotfix for pyarrow is required until our minimum supported pyarrow version is 14.0.1 as is documented here: https://github.com/pitrou/pyarrow-hotfix#readme
> We generally recommend upgrading to PyArrow 14.0.1 or later, but if you cannot upgrade, this package disables the vulnerability on older versions.

But since you have [`pyarrow==17.0.0`](https://github.com/narwhals-dev/narwhals/actions/runs/10055785067/job/27793203912?pr=587#step:9:84) in your CI run. It should not be needed anymore anymore within Ibis. 

It is better if Ibis does something like this within their pyproject file:
```python
"pyarrow_hotfix; pyarrow<\"14.0.1\"",
```
And reflect this within their code as an optional dependency based on the version of pyarrow.

For now, it is probably the best to do both this PR including adding this line to our `all`.

**Comment by mattijn** [comment]
Reverting my last commit since what I tried doesn't work.
See here what is allowed within hatch for environmental markers: https://hatch.pypa.io/dev/config/dependency/#environment-markers.

**Comment by mattijn** [comment]
Created a separate issue for including pyarrow hotfix within altair itself, https://github.com/vega/altair/pull/3494

**Comment by dangotbanned** [comment]
Just arriving here after updating these:
- [`8f15836` (#3492)](https://github.com/vega/altair/pull/3492/commits/8f15836c927515cc833c28394a0caed04ba49d83)
- [`e9a054c` (#3488)](https://github.com/vega/altair/pull/3488/commits/e9a054caba1b0acfa2acaa7434dadd0bfbb430be)

Hi everyone

**Comment by dangotbanned** [comment]
Would reusing whatever solution this PR ends on be the simplest?

- https://github.com/narwhals-dev/narwhals/pull/591

**Comment by MarcoGorelli** [comment]
thanks both!

cool, so I'll leave this PR as it is, and pyarrow-hotfix in Altair itself can be dealt with separately?

> Created a separate issue for including pyarrow hotfix within altair itself, https://github.com/vega/altair/pull/3494

#3495 ?

**Comment by dangotbanned** [comment]
> > Created a separate issue for including pyarrow hotfix within altair itself, #3494
> 
> #3495 ?

Yeah this one rattled me as well

**Comment by mattijn** [comment]
Circular references forward😵‍💫. Merging this, thanks!

**Pull request merged**
