### PR TITLE
feat(typing): Fully annotate `api.py`

### PR DESCRIPTION
**Pull request by dangotbanned**
This could later be extended to other modules, but for now `api` is complete.

Follows work in #3480

---

Main motivation for this was trying to understand all of the private functions.

There seems to be an assumption that `ChartType`'s can be combined with `dict`'s early on (`_check_if_valid_subspec`, `_check_if_can_be_layered`), but later code assumes all derive `SchemaBase`.

# Minimal Repro

<details>
<summary>Test code block</summary>

```py
import altair as alt
import pytest
import pandas as pd

@pytest.mark.parametrize("concat_func", [alt.concat, alt.hconcat, alt.vconcat])
def test_compound_dict(concat_func):
    data = pd.DataFrame({"x": range(3), "y": list("abc")})
    base = alt.Chart(data).mark_point().encode(x="x", y="y")
    mapping = base.to_dict()

    without_top_level = {
        k: v for k, v in mapping.items() if k not in alt.TOPLEVEL_ONLY_KEYS
    }

    compound_1 = concat_func(base, base)
    with pytest.raises(
        ValueError, match=r"Objects with .+ attribute cannot be used within.+Concat"
    ):
        compound_2 = concat_func(base, mapping)

    compound_3 = concat_func(base, without_top_level)

```

</details>

<details>
<summary>Test Failures</summary>

```py
============================= test session starts =============================
platform win32 -- Python 3.12.3, pytest-8.3.2, pluggy-1.5.0
configfile: pyproject.toml
plugins: anyio-4.4.0, cov-5.0.0, xdist-3.6.1
created: 3/3 workers
3 workers [3 items]

FFF                                                                      [100%]
================================== FAILURES ===================================
_________________________ test_compound_dict[hconcat] _________________________

concat_func = <function hconcat at 0x00000114F93D96C0>

    @pytest.mark.parametrize("concat_func", [alt.concat, alt.hconcat, alt.vconcat])
    def test_compound_dict(concat_func):
        data = pd.DataFrame({"x": range(3), "y": list("abc")})
        base = alt.Chart(data).mark_point().encode(x="x", y="y")
        mapping = base.to_dict()
    
        without_top_level = {
            k: v for k, v in mapping.items() if k not in alt.TOPLEVEL_ONLY_KEYS
        }
    
        compound_1 = concat_func(base, base)
        with pytest.raises(
            ValueError, match=r"Objects with .+ attribute cannot be used within.+Concat"
        ):
            compound_2 = concat_func(base, mapping)
    
>       compound_3 = concat_func(base, without_top_level)

tests\vegalite\v5\test_api.py:1197: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
altair\vegalite\v5\api.py:4159: in hconcat
    return HConcatChart(hconcat=charts, **kwargs)  # pyright: ignore
altair\vegalite\v5\api.py:4074: in __init__
    self.data, self.hconcat = _combine_subchart_data(self.data, self.hconcat)
altair\vegalite\v5\api.py:4500: in _combine_subchart_data
    if subdata is not Undefined and all(c.data is subdata for c in subcharts):
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

.0 = <list_iterator object at 0x00000114FBA5E770>

>   if subdata is not Undefined and all(c.data is subdata for c in subcharts):
E   AttributeError: 'dict' object has no attribute 'data'

altair\vegalite\v5\api.py:4500: AttributeError
_________________________ test_compound_dict[concat] __________________________

concat_func = <function concat at 0x000001ADE78BD080>

    @pytest.mark.parametrize("concat_func", [alt.concat, alt.hconcat, alt.vconcat])
    def test_compound_dict(concat_func):
        data = pd.DataFrame({"x": range(3), "y": list("abc")})
        base = alt.Chart(data).mark_point().encode(x="x", y="y")
        mapping = base.to_dict()
    
        without_top_level = {
            k: v for k, v in mapping.items() if k not in alt.TOPLEVEL_ONLY_KEYS
        }
    
        compound_1 = concat_func(base, base)
        with pytest.raises(
            ValueError, match=r"Objects with .+ attribute cannot be used within.+Concat"
        ):
            compound_2 = concat_func(base, mapping)
    
>       compound_3 = concat_func(base, without_top_level)

tests\vegalite\v5\test_api.py:1197: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
altair\vegalite\v5\api.py:4062: in concat
    return ConcatChart(concat=charts, **kwargs)  # pyright: ignore
altair\vegalite\v5\api.py:3977: in __init__
    self.data, self.concat = _combine_subchart_data(self.data, self.concat)
altair\vegalite\v5\api.py:4500: in _combine_subchart_data
    if subdata is not Undefined and all(c.data is subdata for c in subcharts):
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

.0 = <list_iterator object at 0x000001ADE9EAA590>

>   if subdata is not Undefined and all(c.data is subdata for c in subcharts):
E   AttributeError: 'dict' object has no attribute 'data'

altair\vegalite\v5\api.py:4500: AttributeError
_________________________ test_compound_dict[vconcat] _________________________

concat_func = <function vconcat at 0x000002B4F53CDD00>

    @pytest.mark.parametrize("concat_func", [alt.concat, alt.hconcat, alt.vconcat])
    def test_compound_dict(concat_func):
        data = pd.DataFrame({"x": range(3), "y": list("abc")})
        base = alt.Chart(data).mark_point().encode(x="x", y="y")
        mapping = base.to_dict()
    
        without_top_level = {
            k: v for k, v in mapping.items() if k not in alt.TOPLEVEL_ONLY_KEYS
        }
    
        compound_1 = concat_func(base, base)
        with pytest.raises(
            ValueError, match=r"Objects with .+ attribute cannot be used within.+Concat"
        ):
            compound_2 = concat_func(base, mapping)
    
>       compound_3 = concat_func(base, without_top_level)

tests\vegalite\v5\test_api.py:1197: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
altair\vegalite\v5\api.py:4258: in vconcat
    return VConcatChart(vconcat=charts, **kwargs)  # pyright: ignore
altair\vegalite\v5\api.py:4171: in __init__
    self.data, self.vconcat = _combine_subchart_data(self.data, self.vconcat)
altair\vegalite\v5\api.py:4500: in _combine_subchart_data
    if subdata is not Undefined and all(c.data is subdata for c in subcharts):
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

.0 = <list_iterator object at 0x000002B4F79EA710>

>   if subdata is not Undefined and all(c.data is subdata for c in subcharts):
E   AttributeError: 'dict' object has no attribute 'data'

altair\vegalite\v5\api.py:4500: AttributeError
=========================== short test summary info ===========================
FAILED tests/vegalite/v5/test_api.py::test_compound_dict[hconcat] - AttributeError: 'dict' object has no attribute 'data'
FAILED tests/vegalite/v5/test_api.py::test_compound_dict[concat] - AttributeError: 'dict' object has no attribute 'data'
FAILED tests/vegalite/v5/test_api.py::test_compound_dict[vconcat] - AttributeError: 'dict' object has no attribute 'data'
============================== 3 failed in 3.54s ==============================
Finished running tests!
```

</details>

## Summary

Without typing information, finding this the conflict between [`_combine_subchart_data`](https://github.com/vega/altair/blob/1939ebda6101eae77e254c5ffb90a3cf0ad4d6b4/altair/vegalite/v5/api.py#L4486) and the earlier [`_check_if_valid_subspec`](https://github.com/vega/altair/blob/1939ebda6101eae77e254c5ffb90a3cf0ad4d6b4/altair/vegalite/v5/api.py#L3748), [`_check_if_can_be_layered`](https://github.com/vega/altair/blob/1939ebda6101eae77e254c5ffb90a3cf0ad4d6b4/altair/vegalite/v5/api.py#L3781) is much less clear.

# Suggestion

Either all of these functions should expect `SchemaBase | dict` or all `SchemaBase`.

Unless I'm missing something, there does not seem to be a way to use a `dict` to build a compound chart this way.

### CODE REVIEW

**Review by binste — APPROVED** [review]
It's very satisfying to see `api.py` finally being fully typed :) Didn't have it in me when doing #3143 to go all the way. Thanks!

> Either all of these functions should expect SchemaBase | dict or all SchemaBase.
>
> Unless I'm missing something, there does not seem to be a way to use a dict to build a compound chart this way.

Thanks for uncovering it! Agree with your suggestion, dicts don't make sense at this stage.

**Comment by dangotbanned** [comment]
> It's very satisfying to see `api.py` finally being fully typed :) Didn't have it in me when doing #3143 to go all the way. Thanks!

Honestly the amount you *did* do is no small feat, I'm super appreciative of all that work.

Thanks for that and the review @binste

**Comment by binste** [comment]
Thanks! ❤️

**Comment by dangotbanned** [comment]
> > Either all of these functions should expect SchemaBase | dict or all SchemaBase.
> > Unless I'm missing something, there does not seem to be a way to use a dict to build a compound chart this way.
> 
> Thanks for uncovering it! Agree with your suggestion, dicts don't make sense at this stage.

@binste would it be worth opening an issue for the [*Minimal Repro*](https://github.com/vega/altair/pull/3508#issue-2435775279) section?

I'd still need to double-check the implications of this, but it should mean these two could be simplified significantly:

https://github.com/vega/altair/blob/a84783359b933b371dad1d1f1233304c5daf84e5/altair/vegalite/v5/api.py#L3844-L3874

https://github.com/vega/altair/blob/a84783359b933b371dad1d1f1233304c5daf84e5/altair/vegalite/v5/api.py#L3877-L3912

Since `dict[str, Any]` will be rejected later, even if these pass

**Pull request merged**
