### PR TITLE
Initial draft of ipython widget for Altair.

### PR DESCRIPTION
**Pull request by ellisonbg**
See the new example notebook for details.

### CODE REVIEW

**Comment by aggFTW** [comment]
Continuing the conversation from https://github.com/quantopian/qgrid/issues/44
here because it seems issues are not related.

I'm having trouble understanding the purpose of the Output widget if display is not to be used there. How can we refresh the content of Output?

Please look at my on_render method here: https://github.com/aggFTW/altair/blob/ce991cf9b8526ee52431834e455ecdfc6cd58052/altair/view.py

it would also be very useful if you could comment on the overall direction I'm taking this in.

Thanks for starting this @ellisonbg!

**Comment by ellisonbg** [comment]
I think the qgrid stuff should be outside of Altair as it is not directly
visualization related. Here is what I am thinking:

* In altair we can have a set of widget that both configure and render a
visualization.
* We can submit PRs to qgrid itself to add more features to it.
* Somewhere else, we can add the very small amount of code that ties it all
together. That might even be something that you load yourself into all
notebooks, or sparkmagic.

The nice thing about widgets is that widgest from different libraries can
be combined and nested into arbitrary layouts with any desired interaction
very easily.

On Mon, Nov 2, 2015 at 9:04 PM, Alejandro Guerrero Gonzalez <
notifications@github.com> wrote:

> Continuing the conversation from quantopian/qgrid#44
> <https://github.com/quantopian/qgrid/issues/44>
> here because it seems issues are not related.
>
> I'm having trouble understanding the purpose of the Output widget if
> display is not to be used there. How can we refresh the content of Output?
>
> Please look at my on_render method here:
> https://github.com/aggFTW/altair/blob/ce991cf9b8526ee52431834e455ecdfc6cd58052/altair/view.py
>
> it would also be very useful if you could comment on the overall direction
> I'm taking this in.
>
> Thanks for starting this @ellisonbg <https://github.com/ellisonbg>!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ellisonbg/altair/pull/81#issuecomment-153216890>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by aggFTW** [comment]
Do you think that a valid visualization option is the data as a table? (No vegalite viz)

**Comment by ellisonbg** [comment]
I think that make *total* sense, but I don't think that is in the scope of
altair. I think it is important to keep the scope of various projects as
narrow as possible. For example many people will want only table views or
visualizations. Wanting one shouldn't require a user to install the other.
A small, narrow scope are important criteria in the review of incubation
projects to be included in Jupyter.

I think we can help improve qgrid in their repo for all of the additional
things we need the table to do (mostly API changes, and cleanup).

Does this make sense?

On Mon, Nov 2, 2015 at 9:27 PM, Alejandro Guerrero Gonzalez <
notifications@github.com> wrote:

> Do you think that a valid visualization option is the data as a table? (No
> vegalite viz)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ellisonbg/altair/pull/81#issuecomment-153219855>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by aggFTW** [comment]
I agree with the philosophy of keeping scopes narrow. It's good design.

However, I don't understand what you mean by `that make *total* sense, but I don't think that is in the scope of
altair`.  Do you mean that people might want *only* table views or *only* visualizations?

If Altair is only a vega-lite visualizations library, no table view included, I see two options:
1. We could create a new project that injects a table button next to the other visualization options using this widget by building some extension points into the widget.
2. We take this entire widget out of Altair. In the end, it's just using Altair's rendering APIs and this is just a usability layer on top of Altair. We call that project DataVisualizer, where both table and graph options to visualize data are in scope.

Thoughts?

**Comment by ellisonbg** [comment]
Sorry I wasn't clear. Some clarifications:

1. Some users will want automated display of DataFrames as tables (that can
be entirely implemented in qgrid)
2. Some users will want automated display of DataFrames as Altair
visualizations (no tables at all) with a widget based UI (implemented in
altair).
3. Some users will want richer automated display of richer UIs that combine
both qgrid tables and altair visualizations (implemented somewhere outside
altair and qgrid - possibly sparkmagic? Or another project?). This layer
will be super small - perhaps only a few dozens of lines of code. This code
may be so minimal that you end up putting it into a custom startup file
that you ship for now.

I would look at how widgets can be composed easily into complex layouts.
Maybe just try playing with the HBox and VBox widgets and nesting widgets
inside of them. I think that will show you more of how easy 3 will be once
we have done 1 and 2.






On Mon, Nov 2, 2015 at 9:48 PM, Alejandro Guerrero Gonzalez <
notifications@github.com> wrote:

> I agree with the philosophy of keeping scopes narrow. It's good design.
>
> However, I don't understand what you mean by that make *total* sense, but
> I don't think that is in the scope of
> altair. Do you mean that people might want *only* table views or *only*
> visualizations?
>
> If Altair is only a vega-lite visualizations library, no table view
> included, I see two options:
> 1. We could create a new project that injects a table button next to the
> other visualization options using this widget by building some extension
> points into the widget.
> 2. We take this entire widget out of Altair. In the end, it's just using
> Altair's rendering APIs and this is just a usability layer on top of
> Altair. We call that project DataVisualizer, where both table and graph
> options to visualize data are in scope.
>
> Thoughts?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ellisonbg/altair/pull/81#issuecomment-153224518>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by aggFTW** [comment]
I understand what you want to achieve and I've played enough with widgets now that I think I know what code would be needed to achieve that vision. I do understand the very thin layer needed to create a VBox that would flip between table/Altair viz.

That said, I believe that the ability to look at data as tables is very important, to the point that camp of users no. 2 might be so small that Altair could benefit from having the very thin layer to merge 1 and 2 in Altair itself. If the concern is the dependency with qgrid, maybe we could explore just showing the HTML representation of the df and users could opt-in to qgrid.

Having stated my opinion, I'm not an expert in this field and I've only heard Big Data users talk about data, which is a very small sample of users who interact with data and might not be representative of all Altair users.

Do you still think that the thin layer should be outside of Altair?

**Comment by datnamer** [comment]
Cool. I'm interested in this functionality(as are probably others). There is also this :  https://github.com/jupyter/spreadsheet

But not sure if still being built.

**Comment by ellisonbg** [comment]
I understand what you want to achieve and I've played enough with widgets
> now that I think I know what code would be needed to achieve that vision. I
> do understand the very thin layer needed to create a VBox that would flip
> between table/Altair viz.
>
> That said, I believe that the ability to look at data as tables is very
> important, to the point that camp of users no. 2 might be so small that
> Altair could benefit from having the very thin layer to merge 1 and 2 in
> Altair itself. If the concern is the dependency with qgrid, maybe we could
> explore just showing the HTML representation of the df and users could
> opt-in to qgrid.
>
> Having stated my opinion, I'm not an expert in this field and I've only
> heard Big Data users talk about data, which is a very small sample of users
> who interact with data and might not be representative of all Altair users.
>
> Do you still think that the thin layer should be outside of Altair?
>

The other problem is that it increases the scope of Altair in a
semi-arbitrary way that is not directly related to the core goals of the
project. I know that users will want the features you are talking about,
but python packages are cheap and easy to create so I still don't see why
it needs to be in a separate lib.

Another point - I still plan on submitting this as a Jupyter incubation
project. We have been talking about allowing incubation projects to create
new repos in the jupyter-incubator org if needed. We don't want to only
give each incubation project 1 repo as that encourages bad software
engineering practices.

Given this, we might want to put *all* of the UI stuff for tables+altair
into a separate project and keep that stuff entirely out of sparkmagic and
altair. Then I see no problem putting the altair widget and table widget
all together. How does that sound?

Cheers,

Brian





-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by aggFTW** [comment]
That sounds like a good plan. Would the following proposal align well?

I'll keep developing on Altair and create two Widget objects that we can take out to their own repo whenever we want:
1. AltairWidget: Altair viz manipulation object that displays the graphs
2. AltairTableWidget: Tabbed widget that includes data in qgrid in one tab and AltairWidget in the second tab
Please suggest better names if you have them.

Best,
Alejandro

**Comment by ellisonbg** [comment]
This sounds great! Just a warning, I am traveling and have 3 conferences between now and 11/17. Let's keep in touch, but I may be a bit slow to reply.

**Pull request merged**
