### PR TITLE
feat: Upgrade Vega-Lite from 5.17.0 to 5.19.0

### PR DESCRIPTION
**Pull request by binste**
In the first commit, I only changed the version number and ran the code generation. The other commits are manual changes.

### CODE REVIEW

**Review by jonmmease — CHANGES_REQUESTED** [review]
Setting "request changes" to flag that vl-convert doesn't support Vega-Lite 5.19.0 yet.

See https://github.com/vega/altair/discussions/3478#discussioncomment-10054682

**Comment by binste** [comment]
Oh, good point! I somehow stopped half-way through the instructions, sorry for that :) I've now also bumped the version used in JupyterChart.

**Review by jonmmease — APPROVED** [review]
Heh, actually I was confused by my own release notes. Vega-Lite 5.19.0 is already released in vl-convert 1.5, so nothing is blocking there after all!

This PR looks good to go to me!

**Comment by jonmmease** [comment]
Oh, actually, I think we still need to update the vl-convert version in the importer here:

https://github.com/vega/altair/blob/9afd374a83f954e79a5fd6e4f8a8a9c4e5381c04/altair/utils/_importers.py#L44

**Comment by binste** [comment]
I've now updated the vl-convert version in `_importers.py` and `pyproject.toml` as is described in the documentation. Thanks for the review! I'll merge once all tests pass.

**Comment by mattijn** [comment]
Is this issue now appearing https://github.com/vega/altair/issues/3447?

**Pull request merged**
